/*
 *-----------------------------------------------------------------------------
 *
 * monetdbStubs.h --
 *
 *	Stubs for procedures in monetdbStubDefs.txt
 *
 * Generated by genExtStubs.tcl: DO NOT EDIT
 * 2024-09-11 15:44:40Z
 *
 *-----------------------------------------------------------------------------
 */

typedef struct monetdbStubDefs {

    /* Functions from libraries: libmapi */

    Mapi (*mapi_connectPtr)(const char *host, int port, const char *username, const char *password, const char *lang, const char *dbname);
    MapiMsg (*mapi_destroyPtr)(Mapi mid);
    MapiMsg (*mapi_disconnectPtr)(Mapi mid);
    MapiMsg (*mapi_reconnectPtr)(Mapi mid);
    MapiMsg (*mapi_pingPtr)(Mapi mid);
    MapiMsg (*mapi_errorPtr)(Mapi mid);
    char* (*mapi_error_strPtr)(Mapi mid);
    int (*mapi_get_autocommitPtr)(Mapi mid);
    MapiMsg (*mapi_setAutocommitPtr)(Mapi mid, int autocommit);
    MapiHdl (*mapi_preparePtr)(Mapi mid, const char *cmd);
    MapiMsg (*mapi_param_stringPtr)(MapiHdl hdl, int fnr, int sqltype, char *ptr, int *sizeptr);
    MapiMsg (*mapi_param_numericPtr)(MapiHdl hdl, int fnr, int scale, int precision, void *ptr);
    MapiMsg (*mapi_clear_paramsPtr)(MapiHdl hdl);
    MapiMsg (*mapi_executePtr)(MapiHdl hdl);
    MapiMsg (*mapi_fetch_resetPtr)(MapiHdl hdl);
    MapiMsg (*mapi_close_handlePtr)(MapiHdl hdl);
    MapiHdl (*mapi_queryPtr)(Mapi mid, const char *cmd);
    MapiMsg (*mapi_seek_rowPtr)(MapiHdl hdl, mapi_int64 rowne, int whence);
    mapi_int64 (*mapi_fetch_all_rowsPtr)(MapiHdl hdl);
    int (*mapi_fetch_rowPtr)(MapiHdl hdl);
    char* (*mapi_fetch_fieldPtr)(MapiHdl hdl, int fnr);
    int (*mapi_get_field_countPtr)(MapiHdl hdl);
    mapi_int64 (*mapi_get_row_countPtr)(MapiHdl hdl);
    mapi_int64 (*mapi_rows_affectedPtr)(MapiHdl hdl);
    char* (*mapi_get_namePtr)(MapiHdl hdl, int fnr);
    char* (*mapi_get_typePtr)(MapiHdl hdl, int fnr);
    char* (*mapi_get_queryPtr)(MapiHdl hdl);
    int (*mapi_is_connectedPtr)(Mapi mid);
} monetdbStubDefs;
#define mapi_connect (monetdbStubs->mapi_connectPtr)
#define mapi_destroy (monetdbStubs->mapi_destroyPtr)
#define mapi_disconnect (monetdbStubs->mapi_disconnectPtr)
#define mapi_reconnect (monetdbStubs->mapi_reconnectPtr)
#define mapi_ping (monetdbStubs->mapi_pingPtr)
#define mapi_error (monetdbStubs->mapi_errorPtr)
#define mapi_error_str (monetdbStubs->mapi_error_strPtr)
#define mapi_get_autocommit (monetdbStubs->mapi_get_autocommitPtr)
#define mapi_setAutocommit (monetdbStubs->mapi_setAutocommitPtr)
#define mapi_prepare (monetdbStubs->mapi_preparePtr)
#define mapi_param_string (monetdbStubs->mapi_param_stringPtr)
#define mapi_param_numeric (monetdbStubs->mapi_param_numericPtr)
#define mapi_clear_params (monetdbStubs->mapi_clear_paramsPtr)
#define mapi_execute (monetdbStubs->mapi_executePtr)
#define mapi_fetch_reset (monetdbStubs->mapi_fetch_resetPtr)
#define mapi_close_handle (monetdbStubs->mapi_close_handlePtr)
#define mapi_query (monetdbStubs->mapi_queryPtr)
#define mapi_seek_row (monetdbStubs->mapi_seek_rowPtr)
#define mapi_fetch_all_rows (monetdbStubs->mapi_fetch_all_rowsPtr)
#define mapi_fetch_row (monetdbStubs->mapi_fetch_rowPtr)
#define mapi_fetch_field (monetdbStubs->mapi_fetch_fieldPtr)
#define mapi_get_field_count (monetdbStubs->mapi_get_field_countPtr)
#define mapi_get_row_count (monetdbStubs->mapi_get_row_countPtr)
#define mapi_rows_affected (monetdbStubs->mapi_rows_affectedPtr)
#define mapi_get_name (monetdbStubs->mapi_get_namePtr)
#define mapi_get_type (monetdbStubs->mapi_get_typePtr)
#define mapi_get_query (monetdbStubs->mapi_get_queryPtr)
#define mapi_is_connected (monetdbStubs->mapi_is_connectedPtr)
MODULE_SCOPE monetdbStubDefs *monetdbStubs;
